const CARDS = {
  OMEGA_CHAD: {
    id: 'OMEGA_CHAD',
    name: 'Omega Chad Energy',
    emoji: '💀',
    description: 'In 3 turns, all pieces adjacent to both kings are destroyed.',
    type: 'delayed',
    turns: 3,
  },
  PAC_MAN: {
    id: 'PAC_MAN',
    name: 'Pac-Man',
    emoji: '👾',
    description: 'Your pieces can wrap around left/right board edges for 3 turns.',
    type: 'persistent',
    turns: 3,
  },
  HOBBIT_CHARGE: {
    id: 'HOBBIT_CHARGE',
    name: 'Hobbit Charge',
    emoji: '🧙',
    description: 'Only pawns can move for the next 3 turns.',
    type: 'persistent',
    turns: 3,
  },
  DOUBLE_MOVE: {
    id: 'DOUBLE_MOVE',
    name: 'Double Move',
    emoji: '⚡',
    description: 'Take two moves in a row this round.',
    type: 'immediate',
    turns: 1,
  },
  TIME_FREEZE: {
    id: 'TIME_FREEZE',
    name: 'Time Freeze',
    emoji: '🧊',
    description: 'Your opponent must skip their next turn.',
    type: 'immediate',
    turns: 1,
  },
  RESURRECTION: {
    id: 'RESURRECTION',
    name: 'Resurrection',
    emoji: '✨',
    description: 'Place your most recently captured piece on any empty square.',
    type: 'immediate',
    turns: 0,
  },
  KNIGHTS_DOMAIN: {
    id: 'KNIGHTS_DOMAIN',
    name: "Knight's Domain",
    emoji: '🐴',
    description: 'Your knights can also move like bishops for 3 turns.',
    type: 'persistent',
    turns: 3,
  },
  NUCLEAR_PAWN: {
    id: 'NUCLEAR_PAWN',
    name: 'Nuclear Pawn',
    emoji: '💥',
    description: 'When your pawn captures, all adjacent pieces are also destroyed.',
    type: 'persistent',
    turns: 3,
  },
  PAWN_RUSH: {
    id: 'PAWN_RUSH',
    name: 'Pawn Rush',
    emoji: '🏃',
    description: 'All your pawns can advance 2 squares for 3 turns.',
    type: 'persistent',
    turns: 3,
  },
  SWAP_PLACES: {
    id: 'SWAP_PLACES',
    name: 'Swap Places',
    emoji: '🔄',
    description: 'Swap the positions of any two of your pieces.',
    type: 'immediate',
    turns: 0,
  },
};

module.exports = { CARDS };
